### ISSUE TITLE
Implement OpenSimplex Noise Generation

### ISSUE THREAD

**Issue by dulrich** [yzziizzy/c3dlas#2]
Reference links:
- [blog posts](http://uniblock.tumblr.com/)
- digitalshadow [comparison project](https://github.com/digitalshadow/simplex_comparison/tree/master/NoiseTest)
- reddit [thread](https://www.reddit.com/r/proceduralgeneration/comments/2v2mgy/optimizing_opensimplex_part_2_hyperplanes_bit/) with links to C# and C implementation gists

**Comment by yzziizzy** [comment]
https://github.com/yzziizzy/EACSMB/blob/master/src/opensimplex.c
